home:
  path: '/'
  controller: App\Controller\HomeController::index
profile:
  path: /profile
  controller: App\Controller\ProfileController::dashboard

productView:
  path: /profile/products/{id}
  controller: App\Controller\ProductsController::edit

productAdd:
  path: /profile/product/new
  controller: App\Controller\ProductsController::add

productDelete:
  path: /profile/product/delete/{id}
  controller: App\Controller\ProductsController::delete